### ISSUE TITLE
@show_requirements documentation seems misleading.

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPLinter.jl#3]
The docstring for `@show_requirements` suggests that the macro can be invoked as `@show_requirements(solver, problem)`: 
https://github.com/JuliaPOMDP/POMDPLinter.jl/blob/87ecbbb844b3f3c93b4d28124523162cef6e9796/src/requirements_interface.jl#L107

However, I get an error if I try to do that. The only valid invocation seems to be `@show_requirements(POMDPs.solve(solver, problem.))`.

**Comment by zsunberg** [comment]
I looked at this briefly, but couldn't figure out what you meant. The invocation at the end of the first line doesn't match the docstring that you quote. In any case, it is not a high priority.

**Comment by lassepe** [comment]
Oh, you are absolutely right. It must have been late. I'm sorry for the confusion.
