### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by dylan-asmar** [JuliaPOMDP/POMDPLinter.jl#9]
Tests are failing with the current setup.

```julia
implement: Error During Test at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:145
 Unexpected Pass
 Expression: !(#= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:145 =# @implemented(POMDPs.initialstate(::W)))
 Got correct result, please change to @test if no longer broken.

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:149
  Expression: mightbemissing(implemented(gen, Tuple{DDNOut{:sp}, B, Int, Bool, MersenneTwister}))

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:153
  Expression: mightbemissing(#= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:153 =# @implemented(gen(::DDNOut{(:sp, :o, :r)}, ::B, ::Int, ::Bool, ::MersenneTwister)))

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:154
  Expression: mightbemissing(#= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:154 =# @implemented(gen(::DDNOut{(:sp, :o)}, b::B, s::Int, a::Bool, rng::MersenneTwister)))

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:155
  Expression: mightbemissing(#= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:155 =# @implemented(gen(::DDNOut{(:sp, :o, :r)}, b::B, s::Int, a::Bool, rng::MersenneTwister)))

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:158
  Expression: #= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:158 =# @implemented initialstate(::B, ::MersenneTwister)

implement: Test Failed at /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:161
  Expression: #= /Users/dylan/Documents/POMDPLinter.jl/test/runtests.jl:161 =# @implemented initialobs(::B, ::Int, ::MersenneTwister)
```

```julia
julia> versioninfo()
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 10 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 10
```

- Line 145: It appears that `POMDPs.initialstate(::W)` is _not_ implemented and that line should use `@test` instead
- Line 149-155: I'm not sure what `mightbemissing` is supposed to do exactly. When used with `@implemented` it looks like it should always return the result from `@implemented`. `mightbemissing` is defined on line 8 and first calls `ismissing` which is just a test of whether the argument is `nothing` (i.e. `ismissing(x) = x === missing`, in julia-1.9.4 base/essentials.jl). `@implemented` returns `true` or `false` and thus `ismissing` will always return `false`; thus, `mightbemissing` returns, `x` which is the result of `@implemented`.
- Line 161: It doesn't appear that `initialobs(::B, ::I, ::MersenneTwister)` is defined.

**Comment by zsunberg** [comment]
@dylan-asmar , Sorry for the confusion! most of those tests were obsolete in one way or another. I think I fixed in in #10 Feel free to merge that PR once the tests pass (I am going out of town for the next few days)

**Comment by zsunberg** [comment]
I just merged it actually, but the docs are broken. Won't have time to look at it until next week.

**Comment by dylan-asmar** [comment]
Thanks for the fixes! I fixed the documentation issue and merged the test of the travis-ci cleanup and ci updates with https://github.com/JuliaPOMDP/POMDPLinter.jl/pull/12. 
The documentation error was due to having doc strings that weren't included. You can adjust that by passing `checkdocs=:exports` or `checkdocs=:none`.
